# Code copied from tutorials:
# https://www.udemy.com/docker-and-kubernetes-the-complete-guide/

language:            bash
sudo:                required
service:
  - docker

before_install:
# For testing, Dockerfile.dev is used instead of Dockerfile.
- docker build --tag gitlab/gitlab-ce --file Dockerfile.dev .

deploy:
  # Region, bucket name, and keys are stored in environmental variables.
  provider:          elasticbeanstalk
  # Lookup region in the Amazon Elastic Beanstalk console.
  region:            $REGION
  app:               "gitlabce-single-container-test"
  env:               "GitlabceSingleContainerTest-env"
  # Lookup bucket name in the Amazon Elastic Beanstalk console.
  bucket_name:       $BUCKET_NAME
  bucket_path:       "gitlabce-single-container-test"
  # Travis CI should deploy from the master branch instead of testing.
  on:
    branch:          master
  access_key_id:     $AWS_ACCESS_KEY
  secret_access_key:
    secure:          "$AWS_SECRET_KEY"
