# Code copied from tutorials:
# https://www.udemy.com/docker-and-kubernetes-the-complete-guide/

sudo:                required
service:
  - docker

before_install:
- docker build --tag gitlab/gitlab-ce --file Dockerfile.dev .

deploy:
  provider:          elasticbeanstalk
  region:            $REGION
  app:               "gitlabce-single-container-test"
  env:               "GitlabceSingleContainerTest-env"
  bucket_name:       $BUCKET_NAME
  bucket_path:       "gitlabce-single-container-test"
  on:
    branch:          master
  access_key_id:     $AWS_ACCESS_KEY
  secret_access_key:
    secure:          "$AWS_SECRET_KEY"
