web:
  image:                   'gitlab/gitlab-ce:latest'
  restart:                 always
  hostname:
    environment:
      - URL
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url '${URL}:80'
      gitlab_rails['gitlab_shell_ssh_port'] = 22
  ports:
    - '80:80'
    - '22:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
